# Generated by Django 4.2 on 2023-05-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPostApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blogs',
        ),
    ]
